exercise:

    sequence:
      - 1
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0

    repetition:
          - 2
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0

    objects:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0

    mode: 1

    current_exercise: 0

    timeout: 2
