exercise/sequence:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0

exercise/repetition:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0

exercise/objects:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0

exercise/mode: 0
