pointR:
    mat_coordinates:
      - 16
      - 3
    enabled: false
    color: 1

pointL:
    mat_coordinates:
      - 15
      - 3
    enabled: false
    color: 1

point0:
    mat_coordinates:
      - 0 #15
      - 0 #3
    enabled: false
    color: 1
    configuration:
      - 0
      - 0
      - 0
      - 0
      - 0

point1:
    mat_coordinates:
      - 0 #12
      - 0 #6
    enabled: false
    color: 1
    configuration:
      - 0
      - 0
      - 0
      - 0
      - 0


point2:
    mat_coordinates:
      - 0 #19
      - 0 #9
    enabled: false
    color: 1
    configuration:
      - 0
      - 0
      - 0
      - 0
      - 0


point3:
    mat_coordinates:
      - 0 #26
      - 0 #9
    enabled: false
    color: 1
    configuration:
      - 0
      - 0
      - 0
      - 0
      - 0

